[package]
name = "listing_06_dice_game_vrf"
version = "0.1.0"
edition = "2024_07"

[dependencies]
cartridge_vrf = { git = "https://github.com/cartridge-gg/vrf", rev = "f748d4a" }
starknet = "2.13.1"
openzeppelin = "2.0.0"

[dev-dependencies]
snforge_std = "0.51.1"
assert_macros = "2.13.1"

[[target.starknet-contract]]
sierra = true

[scripts]
test = "snforge test"

[tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]
