[package]
name = "listing_99_13_storage_packing"
version = "0.1.0"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest

[dependencies]
# foo = { path = "vendor/foo" }
starknet = ">=2.9.1"

[dev-dependencies]
cairo_test = "2.9.1"
