[package]
name = "listing_03_component_dep"
version = "0.1.0"
edition = "2023_11"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest

[dependencies]
starknet = ">=2.7.0-rc.3"

[[target.starknet-contract]]
