[package]
name = "listing_02_pizza_factory_snfoundry"
version = "0.1.0"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest

[dependencies]
starknet = ">=2.10.0"


[dev-dependencies]
snforge_std = "0.37.0"
assert_macros = "2.10.0"


[[target.starknet-contract]]

[scripts]
test = "snforge test"
