[package]
name = "rename_macro"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
cairo-lang-macro = "0.1.0"
cairo-lang-defs = "2.10.1"
cairo-lang-diagnostics = "2.10.1"
cairo-lang-parser = "2.10.1"
cairo-lang-syntax = "2.10.1"
indoc = "1.0"

[workspace]
