[package]
name = "no_listing_18_negative_impl"
version = "0.1.0"
edition = "2023_11"
experimental-features = ["negative_impls"]

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest

[dependencies]
# foo = { path = "vendor/foo" }
