[package]
name = "hello_macro"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
cairo-lang-macro = "0.1.1"
cairo-lang-parser = "2.13.1"
cairo-lang-syntax = "2.13.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
indoc = "1.0"

[workspace]
