[package]
name = "no_listing_11_assert_eq_ne_macro"
version = "0.1.0"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[cairo]

[dependencies]

[dev-dependencies]
snforge_std = "0.46.0"
assert_macros = "2.11.4"

[scripts]
test = "snforge test"

[tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]
