[package]
name = "source"
version = "0.1.0"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest
# made necessary changes
[dependencies]
starknet = ">=2.7"

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.31.0" }
assert_macros = "2.8.2"

[[target.starknet-contract]]

[scripts]
test = "snforge test"
