
[[questions]]
type = "MultipleChoice"
prompt.prompt = """
Which of the following is **NOT** a benefit of using modules?
"""
prompt.distractors = [
  "Modules provide a scope to avoid naming conflicts across parts of a codebase",
  "Modules group related code so programmers can more easily work on a large codebase",
  "Modules encapsulate implementation details that shouldn't be used by external clients",
]
answer.answer = "Modules boost the runtime performance of interdependent code within the same module"
context = """
Modules have no effect on runtime, they are purely for compile-time organization.
"""
id = "cedb14f3-d1b4-4760-8b32-ab8626372b2c"
