[[questions]]
type = "Tracing"
prompt.program = """
#[derive(Drop)]
struct Character {
    health: u8,
    attack: u8,
}

impl CharacterSub of Sub<Character> {
    fn sub(p1: Character, p2: Character) -> Character {
        Character { health: p1.health - p2.attack, attack: p1.attack }
    }
}

fn main() {
    let mut player1: Character = Character { health: 100, attack: 2 };
    let player2: Character = Character { health: 100, attack: 5 };
    player1 = player1 - player2;
    println!("{}", player1.health); 
}
"""
answer.doesCompile = false
context = "When implementing a trait, the parameter names in the implementing function must match the parameter names specified in the trait definition."
id = "c1d67428-426d-4ffc-a45c-96c2b34ba90f"
