name: Cairo Verify

description: Run the cairo-verify tools on all cairo programs in the book.

runs:
  using: composite
  steps:

    - name: Install cairo-verify
      run: cargo install --path cairo-verify --locked
      shell: bash

    - name: Install dependencies (cairo tools)
      run: |
        curl -L https://github.com/franalgaba/cairo-installer/raw/main/bin/cairo-installer | bash
        echo "CAIRO_ROOT=$HOME/.cairo" >> $GITHUB_ENV
        echo "$HOME/.cairo/target/release" >> $GITHUB_PATH
      shell: bash
      env:
        CAIRO_GIT_TAG: v1.1.0

      - name: Run cairo-verify and generate summary
      run: cairo-verify -q --cairo-root $HOME/.cairo/target/release >> $GITHUB_STEP_SUMMARY
      shell: bash