[package]
name = "listing_07_oz_upgrade"
version = "0.1.0"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
openzeppelin = "0.20.0"
starknet = ">=2.11.4"

[[target.starknet-contract]]
casm = true

[cairo]
enable-gas = true
