[package]
name = "no_listing_01_embeddable"
version = "0.1.0"
edition = "2023_10"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest

[dependencies]
starknet = ">=2.4.0"

[[target.starknet-contract]]
